ARG DEEPHAVEN_SERVER_IMAGE
FROM ${DEEPHAVEN_SERVER_IMAGE}

COPY build/libs/deephaven-sql-username-password-authentication-provider-*-all.jar /apps/libs/deephaven-sql-username-password-authentication-provider.jar