name: Check CI

on:
  pull_request:
    branches: [ 'main', 'rc/v*' ]
  push:
    branches: [ 'main', 'check/**', 'release/v*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup JDK 11
        id: setup-java-11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup JDK 17
        id: setup-java-17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup-java-11.outputs.path }}" >> $GITHUB_ENV

      - name: Setup gradle properties
        run: |
          .github/scripts/gradle-properties.sh >> gradle.properties
          cat gradle.properties
      - name: Check out Jetty
        uses: actions/checkout@v4
        with:
          repository: 'eclipse/jetty.project'
          path: 'jetty.project'
          ref: 'jetty-11.0.24'
          fetch-depth: '0'
      - name: Revert vers bump, and build only what we need for our test
        run: |
          git config --global user.email "colin@colinalworth.com"
          git config --global user.name "colin"
          cd jetty.project
          git checkout cafd30eceb6
          git revert --no-edit 5726603
          mvn clean install -Dmaven.test.skip -DskipTests -am -pl org.eclipse.jetty:jetty-alpn-java-server,org.eclipse.jetty:jetty-alpn-server,org.eclipse.jetty:jetty-bom,org.eclipse.jetty.http2:http2-server,org.eclipse.jetty:jetty-servlet,org.eclipse.jetty:jetty-servlets,org.eclipse.jetty:jetty-webapp,org.eclipse.jetty.websocket:websocket-jakarta-server

      - name: Check
        run: ./gradlew --scan --continue check

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: check-ci-results
          path: |
            **/build/test-results/**
            **/build/reports/tests/**

      - name: Upload JVM Error Logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: check-ci-jvm-err
          path: |
            **/*_pid*.log
            **/core.*
          if-no-files-found: ignore
