name: Deephaven JPY Wheels for publishing

on: push

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py:
         - '3.7'
         - '3.8'
         - '3.9'
#         - '3.10'
#         - '3.11'
        arch: # TODO support this
         - 'x86_64'
#         - 'aarch64'

        exclude:
          - os:  'windows-latest'
            arch: 'aarch64'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }} # Version range or exact version of a Python version to use, using SemVer's version range syntax
#          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python --version
#      - run: '[[ $(python --version) = "Python ${{ matrix.py }}."* ]] || exit "wrong version, expected ${{ matrix.py }} "'
      - run: pip install -U pip
      - run: pip install wheel
      - working-directory: py/jpy/
        run: python3 setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: deephaven_jpy-${{ matrix.py }}-${{ matrix.os }}-${{ matrix.arch }}
          path: py/jpy/dist/*.whl