name: Deephaven JPY Wheels for publishing

on: push

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py:
         - '3.7'
         - '3.8'
         - '3.9'
#         - '3.10'
        arch: # TODO support this
         - 'x86_64'
#         - 'aarch64'

        exclude:
          - os:  'windows-latest'
            arch: 'aarch64'
    steps:
      - uses: actions/checkout@v2
      - uses: gabrielfalcao/pyenv-action@v9
        with:
          default: ${{ matrix.py }}
          command: pip3 install -U pip
      - run: python3 --version
      - run: pip3 install wheel
      - working-directory: py/jpy/
        run: python3 setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: deephaven_jpy-${{ matrix.py }}-${{ matrix.os }}-${{ matrix.arch }}
          path: py/jpy/dist/*.whl