name: Quick CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ 'main', 'check/**', 'release/v*' ]

jobs:
  quick:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch the base revision as well, so reviewdog can see what changed in a PR
          fetch-depth: 2

      - name: Check gitignore rules
        run: .github/scripts/check-gitignore-rules.sh

      - name: Setup JDK 11
        id: setup-java-11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup-java-11.outputs.path }}" >> $GITHUB_ENV

      - name: Setup gradle properties
        run: |
          cat .github/env/${{ runner.os }}/gradle.properties >> gradle.properties
          echo >> gradle.properties
          echo "org.gradle.java.installations.paths=${{ steps.setup-java-11.outputs.path }}" >> gradle.properties
          cat gradle.properties

      - name: Setup ReviewDog to suggest simple fixes
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Quick Task
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: quick-task
          # Even though quick includes spotlessCheck, we want to make sure it runs first and fails ASAP for quick feedback
          arguments: --scan spotlessCheck quick
          gradle-version: wrapper

      - name: Upload JVM Error Logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: quick-ci-jvm-err
          path: '**/*_pid*.log'
          if-no-files-found: ignore
      - name: On build failure, make a diff with fixes, propose them in the pull request
        if: failure() && github.event_name == 'pull_request'
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: create-patch
          arguments: spotlessApply license
          gradle-version: wrapper
      - name: Create review comments based on diff
        if: github.event_name == 'pull_request'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          TMPFILE=$(mktemp)
          git diff > "${TMPFILE}"
          git reset --hard
          reviewdog -f=diff -f.diff.strip=1 -reporter=github-pr-review < "${TMPFILE}"
